### ISSUE TITLE
trying to compile with webpack gives ` Module '"stream"' has no exported member 'TransformCallback'`

### ISSUE THREAD

**Issue by bjdmeest** [rubensworks/sparqljson-parse.js#11]
full log:

```
ERROR in node_modules/sparqljson-parse/lib/SparqlJsonBindingsTransformer.d.ts(2,21): error TS2305: Module '"stream"' has no exported member 'TransformCallback'.
```

Just doing a
```
import {Converter} from 'sparqljson-to-tree';
```

and a webpack using ts-loader

**Comment by rubensworks** [comment]
Should by fixable by adding `@types/node` to your dependencies.

I'll look into adding this as a dependency to this project, so that this won't be needed anymore in the future.

Thanks for reporting!
